import { Router } from "express";
import { Fetch } from "../controller/fetch.controller";
import multer from 'multer';
import { Add } from "../controller/add.controller";
import { validationData,addEvent} from "../service/validation.service";
import { Update } from "../controller/update.controller";
import { Delete } from "../controller/delete.controller";
const upload=multer();
const router=Router();
router.get('/events',Fetch.prototype.fetchEvents);
router.post('/events',upload.single('image'),addEvent,validationData,Add.prototype.addEvent);
router.put('/events/:id',upload.single('image'),Update.prototype.updateEvent);
router.delete('/events/:id',Delete.prototype.EventById);
export=router;